### ISSUE TITLE
Traditionell, unsere Frage:

### ISSUE THREAD

**Issue by SpodoY** [mstrommer/ALDA_Exercise6v12022#1]
![where 7](https://user-images.githubusercontent.com/72346498/174763155-234dbe0e-7537-4957-98b9-ba21b03bbd0b.jpg)

# Bonusmeme
![struggle of mingw](https://user-images.githubusercontent.com/72346498/174763238-471d1826-ab0a-4225-9120-a469211a1ea1.jpg)

**Comment by mstrommer** [comment]
Was war denn das Problem mit dem mingw? ;)

**Comment by SpodoY** [comment]
Also Lokal funktioniert mein Merge-Sort bis heute nicht. Es funktioniert lokal weder mit strcmp noch mit einer eigenen Funktion die kein strcmp verwendet. Ich faile bei circa 2500 Elementen von den ~6000. Am Server funktioniert alles super :(

**Comment by mstrommer** [comment]
Sehr spannend. Das schauen wir uns dann in der Übung an. Das kann ja nicht sein hehe
